
spring:
  application:
    name: server_be
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=PJHK4;TrustServerCertificate=true
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    date-format:yyyy-MM-dd:
  mail:
    host: smtp.gmail.com
    username: khuyenle541@gmail.com
    password: qzjgbglxidzmzibn
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "pDozQy8Ihk/phzNwDBNzRmuWvnA6YkDg/D1mmO4FpejrQJ3kVTf10AcELK1qJnGW"
  valid-duration: 3600 #second
  refreshtable-duration: 360000




