
spring:
  application:
    name: server_be
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=PJHK4;TrustServerCertificate=true;encrypt=false;sendStringParametersAsUnicode=true
    username: sa
    password: 123
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.HttpEncodingAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    date-format:yyyy-MM-dd:
  mail:
    host: smtp.gmail.com
    username: khuyenle541@gmail.com
    password: qzjgbglxidzmzibn
#    username: phamduyhau2000@gmail.com
#    password: tmag jpbi gpcv bnpf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auction-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


jwt:
  signerKey: "pDozQy8Ihk/phzNwDBNzRmuWvnA6YkDg/D1mmO4FpejrQJ3kVTf10AcELK1qJnGW"
  valid-duration: 360000 #second
  refreshtable-duration: 360000

agora:
  appId: "9b1d7859b01d4f7fbb071c2e16681b0f"
  appCertificate: "b3ac1b87350c4b3b99bfe2dbb7663550"
  tokenApiUrl: "https://api:agora:io/v1/token"

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: GLI8RRMU
    secretKey: A7G4E6A8TGB8TO0J2FR4Z574LHJGHUP0
    returnUrl: http://localhost:8080/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other


kafka:
  topic:
    auction:
      success: auction_success_topic
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


