
spring:

  application:
    name: server_be
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://jphk4.database.windows.net:1433;databaseName=auctionlive;encrypt=true;trustServerCertificate=true;loginTimeout=30;
    username: auth
    password: 123lvkLVK
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.HttpEncodingAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    date-format:yyyy-MM-dd:
  mail:
    host: smtp.gmail.com
    username: khuyenle541@gmail.com
    password: qzjgbglxidzmzibn
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    uri: "amqps://ixvxgtrj:NuqKkp-eIyM5bLWNNxeECbNiU-7W_V8_@fuji.lmq.cloudamqp.com/ixvxgtrj"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auction-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  signerKey: "pDozQy8Ihk/phzNwDBNzRmuWvnA6YkDg/D1mmO4FpejrQJ3kVTf10AcELK1qJnGW"
  valid-duration: 360000 #second
  refreshtable-duration: 360000

agora:
  appId: "9b1d7859b01d4f7fbb071c2e16681b0f"
  appCertificate: "b3ac1b87350c4b3b99bfe2dbb7663550"
  tokenApiUrl: "https://api:agora:io/v1/token"

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: GLI8RRMU
    secretKey: A7G4E6A8TGB8TO0J2FR4Z574LHJGHUP0
    returnUrl: http://192.168.1.134:8080/api/v1/payment/vn-pay-callback?source=web
    version: 2.1.0
    command: pay
    orderType: other
  stripe:
    secretKey: sk_test_51QzXY62NueUWgxdgKeJNVZaUT6DdPq0k5HztYTwDtdcYuXvaKg3PeGTiNR5ikoxlZ1tlwjwPaKbjfDsWIXqkCLBN00QTQTahM6
    publishableKey: pk_test_51QzXY62NueUWgxdg6B8LQaTl7VMRdQYocaXHVvi20N3WxUE08zM5gg9JPlRcDZCMNIMXw7ZLsj7YwV6QacadD26L00phbNL9px
    currency: usd
    webhookSecret: whsec_FS1pOMPZt4p4lREbZWJwiNSnXzCvEvCO
kafka:
  topic:
    auction:
      success: auction_success_topic
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


openai:
  api:
    key: "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"  # Thay bằng key của bạn
